/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#pragma once

#include <JuceHeader.h>

// SID Emulator selection: 0=resid-0.16 (default), 1=resid-1.0, 2=libresidfp
#if SID_EMULATOR == 1
    #include "3rdparty/resid-1.0/resid_wrapper.h"
    // Re-export types from resid1 namespace for use in plugin code
    using chip_model = resid1::chip_model;
    using sampling_method = resid1::sampling_method;
    using reg4 = resid1::reg4;
    using reg8 = resid1::reg8;
    using reg12 = resid1::reg12;
    using reg16 = resid1::reg16;
    using reg24 = resid1::reg24;
    using cycle_count = resid1::cycle_count;
    using SID = resid1::SID;
    // Enum values as constexpr for backward compatibility
    constexpr chip_model MOS6581 = resid1::MOS6581;
    constexpr chip_model MOS8580 = resid1::MOS8580;
    constexpr sampling_method SAMPLE_FAST = resid1::SAMPLE_FAST;
    constexpr sampling_method SAMPLE_INTERPOLATE = resid1::SAMPLE_INTERPOLATE;
    constexpr sampling_method SAMPLE_RESAMPLE = resid1::SAMPLE_RESAMPLE;
    constexpr sampling_method SAMPLE_RESAMPLE_FASTMEM = resid1::SAMPLE_RESAMPLE_FASTMEM;
#elif SID_EMULATOR == 2
    #include "3rdparty/resid-fp/residfp_wrapper.h"
    // Re-export types from residfp namespace for use in plugin code
    using chip_model = residfp::chip_model;
    using sampling_method = residfp::sampling_method;
    using reg4 = residfp::reg4;
    using reg8 = residfp::reg8;
    using reg12 = residfp::reg12;
    using reg16 = residfp::reg16;
    using reg24 = residfp::reg24;
    using cycle_count = residfp::cycle_count;
    using SID = residfp::SID;
    // Enum values as constexpr for backward compatibility
    constexpr chip_model MOS6581 = residfp::MOS6581;
    constexpr chip_model MOS8580 = residfp::MOS8580;
    constexpr sampling_method SAMPLE_FAST = residfp::SAMPLE_FAST;
    constexpr sampling_method SAMPLE_INTERPOLATE = residfp::SAMPLE_INTERPOLATE;
    constexpr sampling_method SAMPLE_RESAMPLE = residfp::SAMPLE_RESAMPLE;
    constexpr sampling_method SAMPLE_RESAMPLE_FASTMEM = residfp::SAMPLE_RESAMPLE_FASTMEM;
#else
    #include "3rdparty/resid-0.16/sid.h"
    // resid-0.16 uses global namespace - types are already available after include
    // Enum values are already available in global namespace
    // chip_model enum values: MOS6581, MOS8580
    // sampling_method enum values: SAMPLE_FAST, SAMPLE_INTERPOLATE, SAMPLE_RESAMPLE, SAMPLE_RESAMPLE_FASTMEM
#endif

//==============================================================================
class SIDAudioProcessor;
class SIDEngine
{
public:
    SIDEngine (SIDAudioProcessor& p);

    void prepareToPlay (double sampleRate);
    void processBlock (juce::AudioSampleBuffer& buffer, juce::MidiBuffer& midi);

    void prepareBlock (juce::AudioSampleBuffer& buffer);
    void handleMessage (const juce::MidiMessage& msg);
    void runUntil (int& done, juce::AudioSampleBuffer& buffer, int pos);

    int getNote()               { return lastNote;              }
    int regToCutoff (reg16 val) { return sid.regToCutoff (val); }

    void reset();

private:
    int parameterIntValue (const juce::String& uid);
    float parameterValue (const juce::String& uid);
    bool parameterBoolValue (const juce::String& uid);
    void updateOscs (int curNote);
    void writeReg (uint8_t reg, uint8_t value);

public:
    // Test harness access for register writes
    void testWriteReg(uint8_t reg, uint8_t value) { writeReg(reg, value); }

private:
    SIDAudioProcessor& processor;

    int lastNote = -1;
    int velocity = 0;
    float pitchBend = 0;
    juce::Array<int> noteQueue;

    SID sid;

    std::map<uint8_t, uint8_t> regCache;
public:
    // For test harness access
    const std::map<uint8_t, uint8_t>& getRegCache() const { return regCache; }
};

//==============================================================================
/**
*/
class SIDAudioProcessorEditor;
class SIDAudioProcessor : public gin::Processor
{
public:
    //==============================================================================
    juce::File getProgramDirectory() override;
    juce::Array<juce::File> getFactoryProgramDirectories() override;

    // Get the reSID version string
    juce::String getResidVersion() const;
    
    // Get the SID emulator name
    juce::String getSidEmulatorName() const;

    SIDAudioProcessor();
    ~SIDAudioProcessor() override;

    //==============================================================================
    void prepareToPlay (double sampleRate, int samplesPerBlock) override;
    void releaseResources() override;

    void reset() override;
    void processBlock (juce::AudioSampleBuffer&, juce::MidiBuffer&) override;

    //==============================================================================
    juce::AudioProcessorEditor* createEditor() override;
    bool hasEditor() const override;

    //==============================================================================

    static juce::String paramWave1;
    static juce::String paramPulseWidth1;
    static juce::String paramA1;
    static juce::String paramD1;
    static juce::String paramS1;
    static juce::String paramR1;
    static juce::String paramTune1;
    static juce::String paramFine1;
    static juce::String paramSync1;
    static juce::String paramRing1;
    static juce::String paramWave2;
    static juce::String paramPulseWidth2;
    static juce::String paramA2;
    static juce::String paramD2;
    static juce::String paramS2;
    static juce::String paramR2;
    static juce::String paramTune2;
    static juce::String paramFine2;
    static juce::String paramSync2;
    static juce::String paramRing2;
    static juce::String paramWave3;
    static juce::String paramPulseWidth3;
    static juce::String paramA3;
    static juce::String paramD3;
    static juce::String paramS3;
    static juce::String paramR3;
    static juce::String paramTune3;
    static juce::String paramFine3;
    static juce::String paramSync3;
    static juce::String paramRing3;
    static juce::String paramCutoff;
    static juce::String paramReso;
    static juce::String paramFilter1;
    static juce::String paramFilter2;
    static juce::String paramFilter3;
    static juce::String paramLP;
    static juce::String paramBP;
    static juce::String paramHP;
    static juce::String paramVol;
    static juce::String paramOutput3;
    static juce::String paramVoices;

    gin::AudioFifo fifo {1, 44100};

    // Test harness accessors for sids array
    int getNumVoices() const { return sids.size(); }
    SIDEngine* getVoice(int index) const { return sids[index]; }

private:
    void runUntil (int& done, juce::AudioSampleBuffer& buffer, int pos);
    SIDEngine* findFreeVoice();
    SIDEngine* findVoiceForNote (int note);

    juce::OwnedArray<SIDEngine> sids;
    int nextVoice = 0;

    juce::IIRFilter outputFilter;

    juce::MidiKeyboardState keyboardState;

    //==============================================================================
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (SIDAudioProcessor)

};